configfile: "config.json"
SAMPLECODE=config["samplecode"]
REF=config["reference"]
THR=config["thread"]
rule all:
    input:
        bamfile=expand("bam/{samplecode}.bam", samplecode=SAMPLECODE)

rule bwa:
    input:
        fq1="fastq/{sample}_L001_R1_001.fastq.gz",
        fq2="fastq/{sample}_L001_R2_001.fastq.gz"
    output:
        bam="bam/{sample}.bam"
    params:
        rg="\"@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\"",
        ref=REF
    threads:
        THR
    shell:
        r"""
        bwa mem -t {threads} -M -R {params.rg} {params.ref} {input.fq1} {input.fq2} | \
        samtools view -bh -f3 -F3852 -t{threads} > {output.bam}
        """